hrpsys_gazebo_configuration:
## velocity feedback for joint control, use parameter gains/joint_name/p_v
  use_velocity_feedback: true
## synchronized hrpsys and gazebo
# use_synchronized_command: false
# name of robot (using for namespace)
  robotname: JAXON_JVRC
# joint_id (order) conversion from gazebo to hrpsys, joint_id_list[gazebo_id] := hrpsys_id
  joint_id_list: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32]
# joints list used in gazebo, sizeof(joint_id_list) == sizeof(joints)
  joints:
    - RLEG_JOINT0
    - RLEG_JOINT1
    - RLEG_JOINT2
    - RLEG_JOINT3
    - RLEG_JOINT4
    - RLEG_JOINT5
    - LLEG_JOINT0
    - LLEG_JOINT1
    - LLEG_JOINT2
    - LLEG_JOINT3
    - LLEG_JOINT4
    - LLEG_JOINT5
    - CHEST_JOINT0
    - CHEST_JOINT1
    - CHEST_JOINT2
    - HEAD_JOINT0
    - HEAD_JOINT1
    - RARM_JOINT0
    - RARM_JOINT1
    - RARM_JOINT2
    - RARM_JOINT3
    - RARM_JOINT4
    - RARM_JOINT5
    - RARM_JOINT6
    - RARM_JOINT7
    - LARM_JOINT0
    - LARM_JOINT1
    - LARM_JOINT2
    - LARM_JOINT3
    - LARM_JOINT4
    - LARM_JOINT5
    - LARM_JOINT6
    - LARM_JOINT7
    - LARM_F_JOINT0
    - LARM_F_JOINT1
    - RARM_F_JOINT0
    - RARM_F_JOINT1
    - RANGE_JOINT
  gains:
    CHEST_JOINT0: {p: 3000, d:   1.5, i: 0.0, i_clamp: 0.0}
    CHEST_JOINT1: {p: 2000, d:   1.0, i: 0.0, i_clamp: 0.0}
    CHEST_JOINT2: {p: 2000, d:   1.0, i: 0.0, i_clamp: 0.0}
    HEAD_JOINT0:  {p:  150, d:  0.08, i: 0.0, i_clamp: 0.0}
    HEAD_JOINT1:  {p:  400, d:   0.2, i: 0.0, i_clamp: 0.0}
    RARM_JOINT0:  {p: 1000, d:   0.5, i: 0.0, i_clamp: 0.0}
    RARM_JOINT1:  {p:  400, d:   0.2, i: 0.0, i_clamp: 0.0}
    RARM_JOINT2:  {p:  200, d:   0.1, i: 0.0, i_clamp: 0.0}
    RARM_JOINT3:  {p: 1500, d:   0.7, i: 0.0, i_clamp: 0.0}
    RARM_JOINT4:  {p:  200, d:   0.1, i: 0.0, i_clamp: 0.0}
    RARM_JOINT5:  {p:  400, d:   0.2, i: 0.0, i_clamp: 0.0}
    RARM_JOINT6:  {p:  400, d:   0.2, i: 0.0, i_clamp: 0.0}
    RARM_JOINT7:  {p:  400, d:   0.2, i: 0.0, i_clamp: 0.0}
    LARM_JOINT0:  {p: 1000, d:   0.5, i: 0.0, i_clamp: 0.0}
    LARM_JOINT1:  {p:  400, d:   0.2, i: 0.0, i_clamp: 0.0}
    LARM_JOINT2:  {p:  200, d:   0.1, i: 0.0, i_clamp: 0.0}
    LARM_JOINT3:  {p: 1500, d:   0.7, i: 0.0, i_clamp: 0.0}
    LARM_JOINT4:  {p:  200, d:   0.1, i: 0.0, i_clamp: 0.0}
    LARM_JOINT5:  {p:  400, d:   0.2, i: 0.0, i_clamp: 0.0}
    LARM_JOINT6:  {p:  400, d:   0.2, i: 0.0, i_clamp: 0.0}
    LARM_JOINT7:  {p:  400, d:   0.2, i: 0.0, i_clamp: 0.0}
    RLEG_JOINT0:  {p: 1500, d:   0.7, i: 0.0, i_clamp: 0.0}
    RLEG_JOINT1:  {p: 2000, d:   2.0, i: 0.0, i_clamp: 0.0}
    RLEG_JOINT2:  {p: 3800, d:   4.0, i: 0.0, i_clamp: 0.0}
    RLEG_JOINT3:  {p: 3400, d:   3.0, i: 0.0, i_clamp: 0.0}
    RLEG_JOINT4:  {p: 2800, d:   3.0, i: 0.0, i_clamp: 0.0}
    RLEG_JOINT5:  {p: 2000, d:   2.0, i: 0.0, i_clamp: 0.0}
    LLEG_JOINT0:  {p: 1500, d:   0.7, i: 0.0, i_clamp: 0.0}
    LLEG_JOINT1:  {p: 2000, d:   2.0, i: 0.0, i_clamp: 0.0}
    LLEG_JOINT2:  {p: 3800, d:   4.0, i: 0.0, i_clamp: 0.0}
    LLEG_JOINT3:  {p: 3400, d:   3.0, i: 0.0, i_clamp: 0.0}
    LLEG_JOINT4:  {p: 2800, d:   3.0, i: 0.0, i_clamp: 0.0}
    LLEG_JOINT5:  {p: 2000, d:   2.0, i: 0.0, i_clamp: 0.0}
    LARM_F_JOINT0: {p:  40, d:   0.04, i: 0.0, i_clamp: 0.0}
    LARM_F_JOINT1: {p:  40, d:   0.04, i: 0.0, i_clamp: 0.0}
    RARM_F_JOINT0: {p:  40, d:   0.04, i: 0.0, i_clamp: 0.0}
    RARM_F_JOINT1: {p:  40, d:   0.04, i: 0.0, i_clamp: 0.0}
    RANGE_JOINT:   {p:  40, d:   0.04, i: 0.0, i_clamp: 0.0}
  force_torque_sensors:
    - rfsensor
    - lfsensor
    - rhsensor
    - lhsensor
  force_torque_sensors_config:
## TODO: add translation and rotation
    lfsensor: {joint_name: 'LLEG_JOINT5', frame_id: 'LLEG_LINK5', translation: [0, 0, -0.069], rotation: [0, 0, 1, 3.14159]}
    rfsensor: {joint_name: 'RLEG_JOINT5', frame_id: 'RLEG_LINK5', translation: [0, 0, -0.069], rotation: [0, 0, 1, 3.14159]}
    lhsensor: {joint_name: 'LARM_JOINT7', frame_id: 'LARM_LINK7', translation: [0, 0, -0.069], rotation: [-0.382683, -0.92388, 0, 3.14159]}
    rhsensor: {joint_name: 'RARM_JOINT7', frame_id: 'RARM_LINK7', translation: [0, 0, -0.069], rotation: [-0.382683, -0.92388, 0, 3.14159]}
  imu_sensors:
    - imu_sensor0
  imu_sensors_config:
## TODO: add translation and rotation
     imu_sensor0: {ros_name: 'waist_imu', link_name: 'BODY', frame_id: 'BODY'}
