min_sensor_dist: .2
self_see_default_padding: .01
self_see_default_scale: 1.0
self_see_links:
  - name: BODY
    padding: .05
  - name: RLEG_LINK0
    padding: .05
  - name: RLEG_LINK1
    padding: .05
  - name: RLEG_LINK2
    padding: .05
  - name: RLEG_LINK3
    padding: .05
  - name: RLEG_LINK4
    padding: .05
  - name: RLEG_LINK5
    padding: .05
  - name: LLEG_LINK0
    padding: .05
  - name: LLEG_LINK1
    padding: .05
  - name: LLEG_LINK2
    padding: .05
  - name: LLEG_LINK3
    padding: .05
  - name: LLEG_LINK4
    padding: .05
  - name: LLEG_LINK5
    padding: .05
  - name: CHEST_LINK0
    padding: .05
  - name: CHEST_LINK1
    padding: .05
  - name: CHEST_LINK2
    padding: .05
  - name: HEAD_LINK0
    padding: .05
  - name: HEAD_LINK1
    padding: .05
  - name: RARM_LINK0
    padding: .05
  - name: RARM_LINK1
    padding: .05
  - name: RARM_LINK2
    padding: .05
  - name: RARM_LINK3
    padding: .05
  - name: RARM_LINK4
    padding: .05
  - name: RARM_LINK5
    padding: .05
  - name: RARM_LINK6
    padding: .05
  - name: RARM_LINK7
    padding: .05
  - name: LARM_LINK0
    padding: .05
  - name: LARM_LINK1
    padding: .05
  - name: LARM_LINK2
    padding: .05
  - name: LARM_LINK3
    padding: .05
  - name: LARM_LINK4
    padding: .05
  - name: LARM_LINK5
    padding: .05
  - name: LARM_LINK6
    padding: .05
  - name: LARM_LINK7
    padding: .05
  - name: RANGE_LINK
    padding: .05
  - name: RARM_FINGER0
    padding: .15
  - name: RARM_FINGER1
    padding: .15
  - name: LARM_FINGER0
    padding: .15
  - name: LARM_FINGER1
    padding: .15
